from flask import Flask, render_template, request, jsonify
from web3 import Web3
import requests
from dotenv import load_dotenv
import os
import re
import subprocess  # Import subprocess for running Docker commands

# 加载 .env 文件
load_dotenv(dotenv_path=".env")

app = Flask(__name__)

# 配置以太坊节点连接（这里使用 Infura 示例）
INFURA_URL = os.getenv("INFURA_URL")
web3 = Web3(Web3.HTTPProvider(INFURA_URL))

# GPT-4o-mini API 配置
GPT_API_URL = "https://api.openai.com/v1/chat/completions"
GPT_API_KEY = os.getenv("GPT_API_KEY")
# print("Loaded API Key:", GPT_API_KEY)
# SHARE_DIR = "./share"
SHARE_DIR = os.getenv("SHARE_DIR")

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/get_response", methods=["POST"])
def get_response():
    data = request.json
    recipient = data.get("recipient")
    token = data.get("token")
    amount = data.get("amount")
    intention = data.get("intention")

    # 检查输入是否完整
    if not recipient or not token or not amount or not intention:
        return jsonify({"reply": "Please provide all the required fields: Recipient, Token, Amount, and Intention."})

    # **从保存的文件中读取合约源码**
    source_code_path = os.path.join(SHARE_DIR, f"{recipient}.sol")
    if not os.path.exists(source_code_path):
        return jsonify({"reply": f"Contract code for recipient {recipient} not found. Please fetch it first."})
    try:
        with open(source_code_path, "r", encoding="utf-8") as source_code:
            contract_code = source_code.read()
    except Exception as e:
        return jsonify({"reply": f"Error reading contract code from file: {str(e)}"})
    
    # **从保存的文件中读取合约检测结果**
    slither_path = os.path.join(SHARE_DIR, f"{recipient}_analysis.md")
    if not os.path.exists(slither_path):
        return jsonify({"reply": f"Contract code for recipient {recipient} not found. Please fetch it first."})
    try:
        with open(slither_path, "r", encoding="utf-8") as slither_res:
            slither_content = slither_res.read()
    except Exception as e:
        return jsonify({"reply": f"Error reading contract code from file: {str(e)}"})

    # 构造 GPT 请求的输入内容
    gpt_prompt = (
        f"The recipient address is {recipient}. The token involved is {token}, the amount is {amount}, and the user intention is '{intention}'."
        f" The contract source code is:\n\n{contract_code}\n\n"
        f"The vulnerability analysis report generated by Slither is as follows:\n\n{slither_content}\n\n"
        "Yet the CHECKLIST might not be complete, please analyze the contract for risks and provide suggestions."
    )

    # 调用 GPT API
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {GPT_API_KEY}",
    }
    payload = {
        "model": "gpt-4o-mini",
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": gpt_prompt}
        ]
    }

    try:
        response = requests.post(GPT_API_URL, headers=headers, json=payload)
        response_data = response.json()
        gpt_reply = response_data.get("choices", [{}])[0].get("message", {}).get("content", "No response from the model.")
    except Exception as e:
        gpt_reply = f"Error calling GPT API: {str(e)}"

    # 返回 GPT 的回复
    return jsonify({"reply": gpt_reply})


# @app.route("/get_contract_code", methods=["POST"])
# def get_contract_code():
#     data = request.json
#     recipient = data.get("recipient", "").strip()

#     if not recipient:
#         return jsonify({"error": "Recipient address is required."}), 400

#     if not Web3.is_address(recipient):
#         return jsonify({"error": "Invalid Ethereum address."}), 400

#     try:
#         # 调用 Etherscan API 获取源码
#         ETHERSCAN_API_URL = "https://api.etherscan.io/api"
#         ETHERSCAN_API_KEY = os.getenv("ETHERSCAN_API_KEY")  # 从环境变量中获取 API 密钥
#         print("Loaded API Key:", ETHERSCAN_API_KEY)

#         params = {
#             "module": "contract",
#             "action": "getsourcecode",
#             "address": recipient,
#             "apikey": ETHERSCAN_API_KEY,
#         }

#         # 调用 Etherscan API
#         response = requests.get(ETHERSCAN_API_URL, params=params)
#         response_data = response.json()

#         # 检查 API 返回的状态
#         if response_data["status"] != "1":
#             return jsonify({"error": response_data.get("result", "Error fetching contract source.")}), 400

#         # 获取合约源码
#         source_code = response_data["result"][0].get("SourceCode", "No source code found.")
#         if not source_code:
#             return jsonify({"error": "No source code found at the specified address."}), 404
        
#         # 保存源码到本地 share 目录
#         file_path = os.path.join(SHARE_DIR, f"{recipient}.sol")
#         with open(file_path, "w", encoding="utf-8") as file:
#             file.write(source_code)
            
#         # 提取 Solidity 版本
#         version = extract_solidity_version(source_code)
#         print(f"Extracted Solidity version: {version}")  # 输出到终端
        
#         # 更新 Docker 容器内的 solc 版本
#         CONTAINER_ID = os.getenv("CONTAINER_ID")
#         update_solc_version_in_docker(CONTAINER_ID, version)  # 更新 solc 版本
        
#         # 调用 Docker 进行安全检测
#         CONTAINER_ID = os.getenv("CONTAINER_ID")
#         analysis_result_path = os.path.join(SHARE_DIR, f"{recipient}_analysis.md")  # Define the output path
#         docker_command = (
#             f'docker exec -it {CONTAINER_ID} /bin/bash -c "slither /share/{recipient}.sol --checklist > /share/{recipient}_analysis.md"'
#         )

#         try:
#             subprocess.run(docker_command, shell=True, check=True)  # Run Docker command
#             print(f"Analysis completed and saved to {analysis_result_path}")  # Log the result path
#         except subprocess.CalledProcessError as e:  # Handle Docker errors
#             print(f"Error running Docker command: {e.stderr}")  # Log the error

#         return jsonify({"source": source_code})  # 返回源码
#     except Exception as e:
#         return jsonify({"error": str(e)}), 500

@app.route("/get_contract_code", methods=["POST"])
def get_contract_code():
    data = request.json
    recipient = data.get("recipient", "").strip()

    if not recipient:
        return jsonify({"error": "Recipient address is required."}), 400

    if not Web3.is_address(recipient):
        return jsonify({"error": "Invalid Ethereum address."}), 400

    try:
        # 调用 Etherscan API 获取源码
        ETHERSCAN_API_URL = "https://api.etherscan.io/api"
        ETHERSCAN_API_KEY = os.getenv("ETHERSCAN_API_KEY")  # 从环境变量中获取 API 密钥
        print("Loaded API Key:", ETHERSCAN_API_KEY)

        params = {
            "module": "contract",
            "action": "getsourcecode",
            "address": recipient,
            "apikey": ETHERSCAN_API_KEY,
        }

        # 调用 Etherscan API
        response = requests.get(ETHERSCAN_API_URL, params=params)
        response_data = response.json()

        # 检查 API 返回的状态
        if response_data["status"] != "1":
            return jsonify({"error": response_data.get("result", "Error fetching contract source.")}), 400

        # 获取合约源码
        source_code = response_data["result"][0].get("SourceCode", "No source code found.")
        if not source_code:
            return jsonify({"error": "No source code found at the specified address."}), 404

        # 在 share 下为该地址创建目录
        address_dir = os.path.join(SHARE_DIR, recipient)
        os.makedirs(address_dir, exist_ok=True)

        # 保存源码到对应目录
        source_code_path = os.path.join(address_dir, f"{recipient}.sol")
        with open(source_code_path, "w", encoding="utf-8") as file:
            file.write(source_code)

        # 提取 Solidity 版本
        version = extract_solidity_version(source_code)
        print(f"Extracted Solidity version: {version}")  # 输出到终端

        # 更新 Docker 容器内的 solc 版本
        CONTAINER_ID = os.getenv("CONTAINER_ID")
        update_solc_version_in_docker(CONTAINER_ID, version)  # 更新 solc 版本

        # 调用 Docker 进行安全检测
        analysis_result_path = os.path.join(address_dir, "analysis.md")  # 分析结果保存路径
        docker_command = (
            f'docker exec -it {CONTAINER_ID} /bin/bash -c "slither /share/{recipient}/{recipient}.sol --checklist > /share/{recipient}/analysis.md"'
        )

        try:
            subprocess.run(docker_command, shell=True, check=True)  # 运行 Docker 命令
            print(f"Analysis completed and saved to {analysis_result_path}")  # 记录分析结果路径
        except subprocess.CalledProcessError as e:  # 处理 Docker 错误
            print(f"Error running Docker command: {e.stderr}")  # 输出错误日志

        return jsonify({"source": source_code})  # 返回源码
    except Exception as e:
        return jsonify({"error": str(e)}), 500


# 提取 Solidity 版本的函数
def extract_solidity_version(source_code):
    """
    从 Solidity 源代码中提取版本号
    """
    match = re.search(r"pragma\s+solidity\s+([~^=<>\d.]+);", source_code)  # 匹配 `pragma solidity =0.5.16;`, `^0.8.0;` 等格式
    if match:
        version = match.group(1)  # 提取完整版本号
        # 去掉可能的修饰符（如 `^`, `~`, `=` 等）
        version_number = re.sub(r"[~^=]", "", version)
        return version_number  # 返回纯净的版本号，例如 "0.5.16"
    return "Unknown"  # 如果未匹配到版本号，返回 "Unknown"


# 更新 Docker 容器内 solc 版本的函数
def update_solc_version_in_docker(container_id, version):
    #更新 Docker 容器内的 solc 版本

    if version == "Unknown":
        print("Solidity version not found, skipping update.")
        return
    
    version_number = version.replace("^", "").replace("~", "")
    # Install and switch version
    docker_command_install_solc = (f'docker exec -it {container_id} solc-select install {version_number}'  )
    docker_command_use_solc = (f'docker exec -it {container_id} solc-select use {version_number}')
    try:
        subprocess.run(docker_command_install_solc, shell=True, check=True)
        subprocess.run(docker_command_use_solc, shell=True, check=True)
        print(f"Updated solc version in Docker to {version_number}")  # NEW: Log success
    except subprocess.CalledProcessError as e:
        print(f"Error updating solc version in Docker: {e.stderr}")  # NEW: Log errors


if __name__ == "__main__":
    app.run(debug=True)
